### PR TITLE
Filter

### PR DESCRIPTION
**Pull request by dospuntos**
Filtering is working now.

- Transaction view will indicate if a filter is active
- Search is case insensitive
- Amount box only accepts numbers and `-`
- Input is sanitized before querying DB

### CODE REVIEW

**Comment by korli** [comment]
nullptr isn't known to GCC2.

**Comment by humdingerb** [comment]
> nullptr isn't known to GCC2.

True. But since there are no addons  or replicants, we maybe should just build with gcc13 on 32bit Haiku as well.

**Comment by korli** [comment]
> True. But since there are no addons or replicants, we maybe should just build with gcc13 on 32bit Haiku as well.

I mean, we usually use NULL on Haiku.

**Comment by humdingerb** [comment]
> I mean, we usually use NULL on Haiku.

Right. If that's the only non-gcc2-digestible feature, that should be easily nulled...

Generally speaking, would using gcc13+ be recommended? One (naively mayhaps) would assume that decades of gcc development benefitted the produced binary...

**Comment by dospuntos** [comment]
I'll update the PR soon with some fixes, and remove the nullptr.

GCC2 isn't really holding back on anything yet (except updating the CppSQLite3 library – which isn't urgent), so I think it makes sense to have at least one more release for GCC2.

**Comment by humdingerb** [comment]
👍

**Comment by dospuntos** [comment]
@humdingerb - the filter should now be kept when changing accounts, and I think the filter function is ready to be merged. Unless you have any observations or improvements, of course.

**Comment by humdingerb** [comment]
Works perfectly, and IMO filtering on notification seems quite elegant... :)
Let's merge then!

**Pull request merged**
