### PR TITLE
Manage "Type" within a category

### PR DESCRIPTION
**Pull request by humdingerb**

### CODE REVIEW

**Comment by humdingerb** [comment]
@dospuntos , currently the "Type" column is still visible to help testing. If everything works it will be removed.

You can test by creating new transaction with existing categories, or leave the category empty, or enter a new category. Alerts should pop up when needed to ask for the type of the transaction (income/spending.

If all works, we can merge your #62 before this one and I can fix any conflicts first.

**Comment by dospuntos** [comment]
Very nice, another great improvement. Works great as far a I have been able to test. 👏 

WRT merging and #62 , any order is fine with me. Let me know if you think it's easier to merge this first, and I'll rebase/fix my PR.

**Comment by dospuntos** [comment]
Oh, and I think this fixes #10, right?

**Comment by humdingerb** [comment]
Since your #62 could be applied to this PR without conflicts, yours went first. :)

I've added two more commits to this PR:

* Disallow categories "Transfer" and "Uncategorized", too
* Make alerts a bit wider

The first one is really needed, because the user must be prevented from using those categories for their transactions. The second is an aesthetic change. With the alert text becoming a bit longer it really stood out that the window fast very narrow, but tall...

**Pull request merged**
