### PR TITLE
Add vector icon

### PR DESCRIPTION
**Pull request by dospuntos**
This is an attempt to recreate the current logo in Icon-O-Matic for better scaling and transparent background.

Related to issue #3 , but not really a new design.

CapitalBe icons

### CODE REVIEW

**Comment by korli** [comment]
@humdingerb could you please review?

**Comment by humdingerb** [comment]
Normally, the outer border of objects is thicker. Try a 2pt stroke.
Maybe try to duplicate the "Glyph B" shape and add a dark Contour transformer to increase the contrast between the white letter and the green background. Maybe. Dunno if it can be made to look good.. Or maybe a slightly darker green gradient?
Anyway, border thing is the main thing...

**Comment by dospuntos** [comment]
Thank you for the review, @humdingerb, I've updated the PR with an improved icon. The border is now 2px. 
I tried to add a border to the letter B, but I couldn't get it to look nice and sharp (I've just started with Icon-O-Matic), so I made the green background slightly darker. Please let me know what you think.
 
screenshot 2

**Comment by humdingerb** [comment]
It's good! Merge!

**Pull request merged**
