### PR TITLE
Improved helpfile handling

### PR DESCRIPTION
**Pull request by humdingerb**
* Don't look for the helpfiles in the app's dir, but in one of the B_FIND_PATH_DOCUMENTATION_DIRECTORY, e.g. /system/documentation.

  As a fallback if nothing is found there, try the app's "helpfiles" folder. This makes testing stuff while developing easier. All this much inspired by how Tipster handles its tip files.

* For the above fallback, put the binary in the topfolder.

* Don't rely on the translators to adjust the path ("../English/..", but get the currently set locale.

* Use standard iso names for the language folder names, eg. "es_419".

* Removed gAppPath as no longer needed.

* Open a fixed size help window in the center of the calling window. Esp. when running with a maximized CapitalBe, the help window would needlessly obscure the whole app.

* Close help window on ESCAPE.

* Update en.catkeys

### CODE REVIEW

**Comment by humdingerb** [comment]
@dospuntos , I'd much appreciate your input.

**Comment by dospuntos** [comment]
@humdingerb - these are great improvements, thank you. The only thing I noticed is that the help window title isn't translated. If I'm reading the code right, making it translatable would require the help files to be renamed accordingly?

How and where would the help files be installed when the app is installed?

At some point it would be nice to have HTML help files like ArtPaint and Genio, that supports images and text styling (I added some basic styling using StyleEditor in PR #47 , but the changes are gone, maybe GitHub removed the Haiku attributes?).

**Comment by humdingerb** [comment]
Yep. All attributes get stripped when transferred to github...
HTML docs would be nice, though the current simple file format is 'compatible' to be put up on Polyglot...

I'll have a look at translating the help window title. Probably just add the translated version just for the title...

**Comment by humdingerb** [comment]
Oh: 
> How and where would the help files be installed when the app is installed

They'll get moved in the haikuports recipe to /system/documentation/packages/capitalbe

**Comment by dospuntos** [comment]
On a side note, I noticed that the language files uploaded to Polyglot has **a lot** of repeated terms, I would like to try to simplify it a bit to make translation easier. I'm preparing a PR to combine some of them. Is it correct to repeat `#define B_TRANSLATION_CONTEXT "[context]"` in multiple files when they are related?
 
image

**Comment by humdingerb** [comment]
Indeed putting the same #define B_TRANSLATION_CONTEXT around those would do the trick. Unfortunately this means re-translating. But better now than later...

How about I merge #57 and you work on that from there?

**Comment by dospuntos** [comment]
> But better now than later...

Yes, not ideal but I agree.

> How about I merge #57 and you work on that from there?

Sounds great, thanks

**Comment by humdingerb** [comment]
Alright. Done.
Your turn. :)

**Comment by humdingerb** [comment]
OK, I merged your #58 and rebased this PR.
I also renamed the help files, because Polyglot adds a ".txt" to the filenames and there's no sense of keep having to rename themafter an export.

I'll update the catkeys at Polyglot now.

**Pull request merged**
