### PR TITLE
Memo bug + uppercase queries

### PR DESCRIPTION
**Pull request by dospuntos**
- Fix memo not being displayed for the last item in transaction list
- Optimize Account::CountTransactions(void) using SELECT COUNT(*) instead of selecting all rows
- Change SQL  queries to uppercase (for better readability)

### CODE REVIEW

**Comment by humdingerb** [comment]
> Fix memo not being displayed for the last item in transaction list

I don't think I've seen that one. But I trust you tested all this... :)
BTW, do you happen to have test data that isn't my usual "edhgehgd" etc? If so, we could add it to the repo...

Leaving this PR open for a bit, for others to comment.

**Comment by dospuntos** [comment]
> I don't think I've seen that one. But I trust you tested all this... :)

It only happens when the program starts (when loading data from the DB). When entering a new transaction the memo is set correctly (if any), but if you restart the program the last entry will show "No memo". Editing the transaction will bring it back.

> do you happen to have test data

No, but that could be usefull, as I delete my DB quite often to test from scratch. A small trick to add many transactions is to create one, then schedule it to a date in the past (a few years back) and set frequency to "Monthly". Restart CapitalBe and it will fill in all the scheduled transactions. Another option is to export a QIF file and then import it whenever you need it, but it won't bring in custom currencies nor scheduled transactions, and it might be a bit buggy.

**Comment by humdingerb** [comment]
Alright, now I see the last-memo bug... :)

WRT QIF im/export. I used Quicken about 20 years ago for the bit of bookkeeping needed for my father's one-man-firm. Sometimes the Quicken company (Intuit? or something...) would make you update their software even though we didn't really need any new features. But they apparently slightly changed their file format, so you had to update...

Soon, I just used a spreadsheet with OpenOffice. 100% forwards/backwards compatible, free and open. Never looked back. :)

I'm kinda wary of CapitalBe being another lock-in. Like Gobe documents long, long ago.
No idea how well the QIF im/export works and if it's enough to make it future-proof and the data software-agnostic.
I don't really have a use for bookkeeping software anyway. I'm too lazy to keep my data uptodate. :)

**Comment by dospuntos** [comment]
I've never used Quicken, but it looks like QIF was a common format to share data between programs. I don't know if it's still used, but having options to import/export to common file formats is probably a good way to avoid lock-in. Maybe some kind of CSV export could be useful too? I think I'll take a look at other accounting software like GNU Cash and KMyMoney.

**Pull request merged**
