### PR TITLE
Show warning on failed QIF import

### LINKED ISSUE #5: Import from QIF File doesn't generate errors
When you try to import using any other file (for eg : txt , pdf ) no error is generated .

### PR DESCRIPTION
**Pull request by dospuntos**
Is this enough to close #5 ?

It is just a basic check if anything was imported. QIF-files are simple text files, and the import script runs through each line looking for something to import. If nothing is found, it now returns `false` and displays a message.

Attached is a small QIF file for testing.

[1_qif_example.qif.txt](https://github.com/user-attachments/files/15878515/1_qif_example.qif.txt)

### CODE REVIEW

**Comment by humdingerb** [comment]
Should be good enough, I'd say. Is testing the file for corruption something worth looking into?

I didn't read #5 before testing and just removed parts of the file, but it still got imported. That I read #5, tested with other file types and got the alert alright... :)

BTW, there are some strings in Import.cpp that should be translated. Wanna add those quickly to this PR are would you prefer we do it in a separate one?

**Comment by dospuntos** [comment]
I updated the PR with translations. Let me know if I missed anything.

I did the same thing and removed random parts from a QIF file. I don't know if we can do much to test the integrity of the imported file, it can contain any kind of information, and the script will just import what it's able to understand.

**Comment by humdingerb** [comment]
WRT checking for corruption, one could check if below each ^ delimiter, there's a date, amount, payeeand category. I'm not sure how useful that is... If you think it has merit, you could create a vague issue about it for future exploration.

The changes look good, however you need to change some to sentence-casing, like "Credit card account" etc.

**Comment by dospuntos** [comment]
I was about to update the strings to sentence case, but those are only used as title for the imported accounts, maybe it makes sense to keep them as they are? Just let me know if you disagree and I'll change them.

I'll create an issue for the import/export functions, although working they could need some improvements.

**Comment by humdingerb** [comment]
Personally, I like just sticking to sentence casing for everything. It makes things simple, no wondering about this or that edge case. :)

You may want to consider putting all strings that were inserted while importing between pointy brackets, like <No payee entered>. That way users easily see what they didn't enter and may motivate them to edit, like the account name.

**Comment by dospuntos** [comment]
OK, let's go with that. I've updated the PR and added brackets to the names (I assume you meant these `<>`, they where stripped out of your message).

screenshot

**Comment by humdingerb** [comment]
Yeah, forgot about those code tags for the `<>` again...

Alright, let's merge then. Thanks!

**Pull request merged**
